### ISSUE TITLE
Bi-directional tracker code is incomplete

### ISSUE THREAD

**Issue by hutao568** [Abyssaledge/ImmortalTracker-for-CTRL#1]
There is undefined variable 'inter_ts'，

https://github.com/Abyssaledge/ImmortalTracker-for-CTRL/blob/main/mot_3d/bidirection.py#L22C19-L22C19

**Comment by Abyssaledge** [comment]
I would like to clarify that `bidirection.py` is not the one in our CTRL paper and this is a deprecated file. Sorry for misleading, my bad.
The forward tracking uses `max_time_since_update` parameter to pad missing boxes. And the backward tracking corresponds to `extend_tracks.py` in CTRL repo.

**Comment by hutao568** [comment]
Ok, thank you for your quick answer and wish you a happy Liqiu.
