### ISSUE TITLE
why bidirection_tracking  is not used?

### ISSUE THREAD

**Issue by 20210726** [Abyssaledge/ImmortalTracker-for-CTRL#2]
in main_waymo.py， immortal_for_ctrl_keep10.yaml, bidirection tracking is not used，is the result not good?
        if configs['running'].get('bidirection', False):
            ids, bboxes, states, types = bidirection_sequence_mot(configs, data_loader, file_index)
        else:
            ids, bboxes, states, types = sequence_mot(configs, data_loader, file_index)
        if configs['data_loader'].get('backward', False):

**Comment by dof-pikes** [comment]
@20210726  您好，我最近也在关注这个工作，方便加Q或VX交流讨论吗？

**Comment by Abyssaledge** [comment]
This `bidirectional` is legacy, and not the true `bidirectional` in our paper. This repo only implements forward tracking. Backward tracking is implemented by `extend_tracks.py` in SST repo.

**Comment by Abyssaledge** [comment]
I have deleted this part in case of a misunderstanding.
