### ISSUE TITLE
Tracking Results of CTRL Paper

### ISSUE THREAD

**Issue by JuiceLemonLemon** [Abyssaledge/ImmortalTracker-for-CTRL#3]
@Abyssaledge 
Hello, thank you for your sharing.
I have a question about tracking results in CTRL paper.
Is this result based on your shared immortal_for_ctrl_keep10.yaml which is without bidirection and nms?
I found the tracking result was very low without nms on nuScenes dataset.

![image](https://github.com/Abyssaledge/ImmortalTracker-for-CTRL/assets/35052602/8e494203-5c72-4ef1-ad1f-9f398e35946e)

**Comment by Abyssaledge** [comment]
Bidirectional does not improve tracking performance, which is only good for detection.
For nuScenes, you should refer to the official ImmortalTracker repo. Thanks.

**Comment by JuiceLemonLemon** [comment]
ok, I see. Thank you for your reply.
